# Action that registers Octopus releases in the release-log
name: Register Release

on:
  workflow_call:
    inputs:
      octopus-module-name:
        required: true
        type: string
      release-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      octopus-module-name:
        required: true
        type: string
      release-version:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  
jobs:
  register-release-in-log:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update module file
        run: |
          echo "Register release ${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          if [[ ! -e ${{ inputs.octopus-module-name }}.txt ]]; then
            touch ${{ inputs.octopus-module-name }}.txt
          fi
          echo "${{ inputs.release-version }}" | cat - ${{ inputs.octopus-module-name }}.txt > temp && mv temp ${{ inputs.octopus-module-name }}.txt

      - name: Make git commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff
          git add ${{ inputs.octopus-module-name }}.txt
          git commit -m"${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          git status
          git config --list
          
      - name: Push changes
        uses: ad-m/github-push-action@master
