# Action that registers Octopus releases in the octopus-release-log
# Payload should contain two parameters:
# * octopus-module-name - a name of the Octopus module to register (should match repository name with 'octopusden' prefix) 
# * release-version - a released version to register

name: Register Release

on:
  repository_dispatch:
    types: register-release


permissions:
  contents: write
  pull-requests: write
  
jobs:
  register-release-in-log:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update module file
        run: |
          echo "Register release ${{ github.event.client_payload.octopus-module-name }}-${{ github.event.client_payload.release-version }}"
          if [[ ! -e ${{ github.event.client_payload.octopus-module-name }}.txt ]]; then
            touch ${{ github.event.client_payload.octopus-module-name }}.txt
          fi
          echo "${{ github.event.client_payload.release-version }}" | cat - ${{ github.event.client_payload.octopus-module-name }}.txt > temp && mv temp ${{ github.event.client_payload.octopus-module-name }}.txt

      - name: Make git commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ github.event.client_payload.octopus-module-name }}.txt
          git commit -m"${{ github.event.client_payload.octopus-module-name }}-${{ github.event.client_payload.release-version }}"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
